name: delete aws infra lab1
on:
  workflow_dispatch:
jobs:
  create_plan:
    permissions:
       id-token: write # This is required for requesting the JWT
       contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4
      - name: set-up terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539789378:role/Oidc-admin
          aws-region: ap-south-1
      - name: test aws login
        run: aws sts get-caller-identity
      - name: initialize
        run: terraform init
      - name: plan_destroy
        run: terraform plan -destroy -out myplan
      - name: apply_destroy
        run: terraform apply myplan

